# server name
serverName: Our Server

useEconomy: true

# teleport home using /home command
homes: true
databseForTP: world

database:
  host: localhost # host of your database
  port: 3306 # default port for MariaDB and MySQL
  database: indrocraft # name of your database. A database server can contain multiple databases
  user: root
# if database has no password leave the password as 'PasswordHere'
  password: PasswordHere