name: EconomyRanks
version: ${project.version}
main: indrocraft.spigot.ecnomyranks.Main
api-version: 1.17
commands:
  Complaints:
    usage: /<command>
    description: allows peeps to complain
  Warn:
    usage: /<command>
    description: warns a player
  SetRank:
    usage: /<command>
    description: Sets Players Rank
  Economy:
    usage: /<command>
    description: the money system
    aliases: [eco, e]